let name = window.prompt("Enter your name: ")
let x = window.prompt("Enter a text")
let y = window.prompt("Enter second text")
document.write("Hi!"+name+" your output is "+"<br>")
r1=(x==y)
document.write("Is x=y?"+r1+"<br>")
r2=(x<y)
document.write("Is x<y?"+r2+"<br>")
r3=(x<=y)
document.write("Is x<=y?"+r3+"<br>")
r4=(x>y)
document.write("Is x>y?"+r4+"<br>")
r5=(x!=y)
document.write("Is x!=y?"+r5)
